### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by qianbudiao6** [xustc/SpeakerRecognitionPipeline#1]
What accuracy did you achieve on the THCHS-30 open-source dataset?  thank you

**Comment by xustc** [comment]
Sorry for the late reply.
The accuracy depends on the the threshold you set, thus it might not be a good criterion.
Here I use Equal Error Rate(EER) to evalute the performance. Sadly it is 10%-20% due to the tiny dateset and some other reasons related to para tuning.
You can check the papers to see some nice results.
